# CI to build and test. Copied from github.com/fxamacker/cbor
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  # Test on various OS with default Go version. 
  tests:
    name: Test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        go-version: [1.15.x, 1.16.x, 1.17.x]
        
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        
    - name: Get dependencies
      run: go get -v -t -d ./...
      
    - name: Build project
      run: go build ./...
      
    - name: Run tests
      run: |
        go version
        go test -timeout 30m -race -v ./...
